DifficultKillFormula: 2*($DeadScore$-$KillerScore$)
#击杀高段位人分数计算公式
SimpleKillFormula: $DeadScore$/$KillerGradeScore$+1
#击杀同段位人分数计算公式
EasyKillFormula: $KillerScore$/($KillerScore$-$DeadScore$)
#击杀低段位人分数计算公式
DifficultDieFormula: ($KillerScore$-$DeadScore$)/($DeadScore$/10)
#被高段位人击杀扣分计算公式
SimpleDieFormula: $KillerGradeScore$/100
#被同段位人击杀扣分计算公式
EasyDieFormula: ($DeadScore$-$KillerScore$)*1.5
#被低段位人击杀扣分计算公式
#注意：分数最终结果为整数(向下取整)！
#如果想变成加分或者变成扣分可以添个"0-" 因为1的相反数就是0-1嘛~
#变量表:
#$KillerScore$ - 击杀者分数
#$DeadScore$ - 死者分数
#$KillerGradeScore$ - 击杀者段位所需分数
#$DeadGradeScore$ - 死者段位所需分数
GradeList:
  #Default为默认 不要删除！
  Default:
    Name: "&2青铜"
    Prefix: "&f[&2青铜&f]&a"
    Suffix: "none"
  1:
    Name: "&3白银"
    Score: 100
    Prefix: "&f[&3白银&f]&9"
    Suffix: "none"
  2:
    Name: "&6黄金"
    Score: 500
    Prefix: "&f[&6黄金&f]&e"
    Suffix: "none"
  3:
    Name: "&f铂金"
    Score: 1000
    Prefix: "&e[&f铂金&e]&d"
    Suffix: "none"
#段位设置
#格式
#X:
#  Name: 段位名称 - 必填
#  Score: 达到所需分数 - 必填(Default不需要填)
#  Prefix: 聊天前缀 无则填"none"
#  Suffix: 聊天后缀 无则填"none"
#如Prefix: "none"
#X由任意英文字母和数字组成
#不一定按分数顺序写，但需要避免同分数的出现
#Default为默认 不需要填分数
OpenWorlds:
  - "*"
#开启扣分加分的世界
#*为所有