name: Prestige
version: 1.7.10-0.1.1
author: Himmelt
main: org.soraworld.prestige.Prestige
depend: [Violet]
website: https://github.com/Himmelt/Prestige
description: Prestige Plugin.

commands:
  prestige:
    description: "Prestige - https://github.com/Himmelt/Prestige"
    usage: "/prestige save|reload|lang|debug..."
    permission: prestige.admin
    permission-message: "You have no permission <prestige.admin>"
permissions:
  prestige.admin:
    default: op
