name: Prestige
version: 1.7.10-1.0.7
author: Himmelt
main: org.soraworld.prestige.Prestige
depend: [Violet]
softdepend: [PlaceholderAPI]
website: https://github.com/Himmelt/Prestige
description: Prestige Plugin.

commands:
  prestige:
    description: "Prestige - https://github.com/Himmelt/Prestige"
    usage: "/prestige add|set|info|top|open|close|exec|clvl"
permissions:
  prestige.admin:
    default: op
